# Generated by Django 3.2.9 on 2021-12-05 02:10

import autoslug.fields
from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='plano',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='plano',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
    ]
